// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5jUhDNJLjMdu6sS2GWUPc9pWE60Xp13g',
    appId: '1:78538947089:web:2608975b4e50d0eb598fb0',
    messagingSenderId: '78538947089',
    projectId: 'fir-f3ed9',
    authDomain: 'fir-f3ed9.firebaseapp.com',
    storageBucket: 'fir-f3ed9.appspot.com',
    measurementId: 'G-VN5GTSENM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATgdyWfyzA1MV4xz9IMiLpjBzbKVVScGc',
    appId: '1:78538947089:android:2994184ce8dcd005598fb0',
    messagingSenderId: '78538947089',
    projectId: 'fir-f3ed9',
    storageBucket: 'fir-f3ed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9QnZK9vFAdm3ssuHyrQ8Oz5P6WcPfiT4',
    appId: '1:78538947089:ios:38d33d43425a0584598fb0',
    messagingSenderId: '78538947089',
    projectId: 'fir-f3ed9',
    storageBucket: 'fir-f3ed9.appspot.com',
    iosClientId: '78538947089-3pt4jffdscjrbs8leqmtfujl993binms.apps.googleusercontent.com',
    iosBundleId: 'com.example.fstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9QnZK9vFAdm3ssuHyrQ8Oz5P6WcPfiT4',
    appId: '1:78538947089:ios:38d33d43425a0584598fb0',
    messagingSenderId: '78538947089',
    projectId: 'fir-f3ed9',
    storageBucket: 'fir-f3ed9.appspot.com',
    iosClientId: '78538947089-3pt4jffdscjrbs8leqmtfujl993binms.apps.googleusercontent.com',
    iosBundleId: 'com.example.fstore',
  );
}
