// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB51DfH4_rY4XD-tL0k_45CaXoDMzzSotY',
    appId: '1:269993129984:web:02f05d877c2850287940e5',
    messagingSenderId: '269993129984',
    projectId: 'fstore2-bf7c8',
    authDomain: 'fstore2-bf7c8.firebaseapp.com',
    storageBucket: 'fstore2-bf7c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoJ9tOz87QfdI93fdEd2qgTuCu7HSznTs',
    appId: '1:269993129984:android:2311cc69d9fb21077940e5',
    messagingSenderId: '269993129984',
    projectId: 'fstore2-bf7c8',
    storageBucket: 'fstore2-bf7c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhX7FQkIsFFqiVNh2wWZ5sMFhVXD-bg6A',
    appId: '1:269993129984:ios:40897f67999ecff17940e5',
    messagingSenderId: '269993129984',
    projectId: 'fstore2-bf7c8',
    storageBucket: 'fstore2-bf7c8.appspot.com',
    iosClientId: '269993129984-qs1741kmnp9h8ec7b8ebtcr74bjvhu1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhX7FQkIsFFqiVNh2wWZ5sMFhVXD-bg6A',
    appId: '1:269993129984:ios:40897f67999ecff17940e5',
    messagingSenderId: '269993129984',
    projectId: 'fstore2-bf7c8',
    storageBucket: 'fstore2-bf7c8.appspot.com',
    iosClientId: '269993129984-qs1741kmnp9h8ec7b8ebtcr74bjvhu1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fstore',
  );
}
